language: perl
perl:
    - '5.24'
    - '5.22'
    - '5.20'
    - '5.18'
    - '5.16'
    - '5.14'
    - '5.12'
install: cpanm -n --skip-satisfied Devel::Cover::Report::Coveralls git://github.com/JRaspass/p5-Compiler-Lexer.git
script: PERL5OPT=-MDevel::Cover prove -It -l
after_success: cover -report coveralls -select_re ^lib/
